### PR TITLE
Namespace and variable reference tidying

### PR DESCRIPTION
**Pull request by leonawicz**
Using explicit namespaces and the `.data[[` dataframe variable lookups is good use in packages. Fewer issues on package checking and you don't have to populate the `globalVariables` list with special named variables.

I see a remaining issue in `chords_ngram` but I left it alone because I didn't understand the function. There seems to be reference to a `date` column that doesn't exist. I couldn't understand how to fix it but this function does not run. For this reason I retained the "date" in `globalVariables`. If I could understand this function I could write some unit tests for it.

### CODE REVIEW

**Comment by brunaw** [comment]
Hey Matt. Thanks again for the clever fixes.
 
I honestly don't remember what the column `date` is doing in the `chords_ngram()` function. Possibly I used to have a date column that needed some adjusting, but not anymore, so I can tell you that the code lines that use the `date` column are irrelevant now, might as well just be deleted.

I can't ask you to bother with that, but if you want to change it yourself let me know so I can delay the merge of this pull request :)

**Comment by leonawicz** [comment]
Hey Bruna,

No problem. It was a quick update. It looks like it works now. I don't know what the new `chords_ngram` column is used for. But I noticed it's the only thing in the package that requires the package to take a dependency on `zoo`. You could lighten the dependency load by coding around the need for `rollapply`. Not a big deal of course, just an observation.

**Comment by brunaw** [comment]
Thanks Matt! The idea of the new column is to create something similar to what we do in text analysis when using n-grams, so one can analyze, for instance, what are the most common chord transitions for a specified song or artist. Does that make sense to you?  

Thanks for the tip, though I don't know when I'll have time to improve that (even with it being so simple), hopefully in a few days :)

**Comment by leonawicz** [comment]
That does make sense, thanks! I should add something similar to `tabr`. Thanks for the tip. It reminds me a bit of my `pitch_diff` and `scale_diff` functions that are basically like base R `diff` but for a vector of music notation and you can set the lag. The only difference is those are focused on the intervals n steps apart instead of the ngram sequence.

**Pull request merged**
